version: '3'

services:
  api:
    container_name: ultracar_api
    ports:
      - "5230:8080"
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=postgres
    depends_on:
      - postgres

  postgres:
    container_name: ultracar_db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senhacriativa
      POSTGRES_DB: postgresDB
    ports:
      - "5432:5432"


