version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senhacriativa
      POSTGRES_DB: postgresDB
    ports:
      - "5432:5432"


